[package]
name = "ttpserver"
version = "0.1.0"
authors = ["eulerf <2331249337@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
